FROM golang:GO_VERSION

LABEL maintainer="ml@akabos.com" \
	  go.version="GO_VERSION" \
	  android.ndk.version="NDK_VERSION"

COPY sources.list /etc/apt/

RUN apt-get update \
 && apt-get upgrade -y \
 && DEBIAN_FRONTEND=noninteractive \
 	apt-get install -y \
 	build-essential google-android-platform-24-installer gradle \
 && apt-get clean

RUN cd /opt \
 && curl -O https://dl.google.com/android/repository/NDK_FILENAME \
 && echo NDK_CHECKSUM | sha1sum NDK_FILENAME \
 && unzip -o NDK_FILENAME \
 && rm NDK_FILENAME

ENV PATH=/opt/NDK_DIRNAME:${PATH}
ENV ANDROID_SDK=/usr/lib/android-sdk

RUN go get -u golang.org/x/mobile/cmd/gomobile \
 && gomobile init -ndk /opt/NDK_DIRNAME
